name: Feature Request
description: Request a feature to be added to the API code.
labels: ["enhancement", "Needs Review"]
body:

  - type: textarea
    id: describe-the-feature
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: This issue is related to the self-hosting code and not an API or Home Assistant feature request.
          required: true
        - label: I have written an informative title.
          required: true
