"""Static MCP resources for the Pirate Weather proxy server."""

from __future__ import annotations

from typing import Any

FORECAST_BLOCK_METADATA: dict[str, Any] = {
    "forecast": {
        "tool": "get_forecast",
        "description": "Compact forecast response with current conditions, this hour, next hour, today, tomorrow, alerts, and summary text.",
        "returned_fields": [
            "currently",
            "this_hour",
            "next_hour",
            "today",
            "tomorrow",
            "alerts",
            "summary_text",
            "flags",
        ],
    },
    "currently": {
        "tool": "get_current_weather",
        "description": "Current conditions for the requested point.",
        "returned_fields": [
            "time",
            "summary",
            "icon",
            "nearestStormDistance",
            "precipIntensity",
            "precipProbability",
            "temperature",
            "apparentTemperature",
            "dewPoint",
            "humidity",
            "pressure",
            "windSpeed",
            "windGust",
            "windBearing",
            "cloudCover",
            "uvIndex",
            "visibility",
            "ozone",
        ],
    },
    "minutely": {
        "tool": "get_minutely_forecast",
        "description": "Minute-by-minute precipitation forecast.",
        "returned_fields": ["summary", "icon", "data"],
        "data_fields": [
            "time",
            "precipIntensity",
            "precipProbability",
            "precipIntensityError",
        ],
    },
    "hourly": {
        "tool": "get_hourly_forecast",
        "description": "Hourly forecast entries, limited by the hours argument.",
        "returned_fields": ["summary", "icon", "data"],
        "data_fields": [
            "time",
            "summary",
            "icon",
            "precipIntensity",
            "precipProbability",
            "precipAccumulation",
            "precipType",
            "temperature",
            "apparentTemperature",
            "dewPoint",
            "humidity",
            "pressure",
            "windSpeed",
            "windGust",
            "windBearing",
            "cloudCover",
            "uvIndex",
            "visibility",
            "ozone",
        ],
    },
    "daily": {
        "tool": "get_daily_forecast",
        "description": "Daily forecast entries, limited by the days argument.",
        "returned_fields": ["summary", "icon", "data"],
        "data_fields": [
            "time",
            "summary",
            "icon",
            "sunriseTime",
            "sunsetTime",
            "moonPhase",
            "precipIntensity",
            "precipIntensityMax",
            "precipProbability",
            "precipAccumulation",
            "precipType",
            "temperatureHigh",
            "temperatureLow",
            "apparentTemperatureHigh",
            "apparentTemperatureLow",
            "dewPoint",
            "humidity",
            "pressure",
            "windSpeed",
            "windGust",
            "windBearing",
            "cloudCover",
            "uvIndex",
            "visibility",
            "ozone",
        ],
    },
    "alerts": {
        "tool": "get_alerts",
        "description": "Weather alerts for the requested point when alert sources are available.",
        "returned_fields": ["alerts"],
        "alert_fields": [
            "title",
            "regions",
            "severity",
            "time",
            "expires",
            "description",
            "uri",
        ],
    },
    "flags": {
        "description": "Response metadata including units, version, and source metadata.",
        "returned_with_block_tools": True,
    },
}

EXAMPLE_USAGE: list[dict[str, Any]] = [
    {
        "name": "Current forecast, next hour, tomorrow, and alerts",
        "tool": "get_forecast",
        "arguments": {"latitude": 45.4215, "longitude": -75.6972, "units": "ca"},
    },
    {
        "name": "Current weather in Ottawa",
        "tool": "get_current_weather",
        "arguments": {"latitude": 45.4215, "longitude": -75.6972, "units": "ca"},
    },
    {
        "name": "Next 12 hourly forecasts",
        "tool": "get_hourly_forecast",
        "arguments": {
            "latitude": 45.4215,
            "longitude": -75.6972,
            "hours": 12,
            "units": "si",
        },
    },
    {
        "name": "Tomorrow forecast",
        "tool": "get_tomorrow_forecast",
        "arguments": {"latitude": 32.7157, "longitude": -117.1611, "units": "us"},
    },
    {
        "name": "Daily forecast for a week",
        "tool": "get_daily_forecast",
        "arguments": {
            "latitude": 51.5072,
            "longitude": -0.1276,
            "days": 7,
            "units": "uk2",
        },
    },
    {
        "name": "Historical weather by UNIX timestamp",
        "tool": "get_historical_weather",
        "arguments": {
            "latitude": 47.1756,
            "longitude": 27.594,
            "time": "1730869200",
            "units": "si",
        },
    },
    {
        "name": "Concise weather summary",
        "tool": "get_weather_summary",
        "arguments": {"latitude": -33.8688, "longitude": 151.2093, "units": "si"},
    },
    {
        "name": "Check upstream FastAPI reachability",
        "tool": "test_api_connection",
        "arguments": {},
    },
]
