# Model variable indices for human-readable access
# Add more mappings as needed for each model

HRRR_SUBH = {
    "gust": 1,
    "pressure": 2,
    "temp": 3,
    "dew": 4,
    "wind_u": 5,
    "wind_v": 6,
    "intensity": 7,
    "snow": 8,
    "ice": 9,
    "freezing_rain": 10,
    "rain": 11,
    "refc": 12,
    "accum": 13,
    "vis": 14,
    "specific_humidity": 15,
    "solar": 16,
}
HRRR = {
    "vis": 1,
    "gust": 2,
    "pressure": 3,
    "temp": 4,
    "dew": 5,
    "humidity": 6,
    "wind_u": 7,
    "wind_v": 8,
    "intensity": 9,
    "accum": 10,
    "snow": 11,
    "ice": 12,
    "freezing_rain": 13,
    "rain": 14,
    "cloud": 15,
    "smoke": 16,
    "refc": 17,
    "solar": 18,
    "cape": 19,
}

GFS = {
    "vis": 1,
    "gust": 2,
    "pressure": 3,
    "temp": 4,
    "dew": 5,
    "humidity": 6,
    "apparent": 7,
    "wind_u": 8,
    "wind_v": 9,
    "intensity": 10,
    "accum": 11,
    "snow": 12,
    "ice": 13,
    "freezing_rain": 14,
    "rain": 15,
    "ozone": 16,
    "cloud": 17,
    "uv": 18,
    "storm_dist": 19,
    "storm_dir": 20,
    "refc": 21,
    "solar": 22,
    "cape": 23,
    "station_pressure": 24,
}

GEFS = {
    "prob": 1,
    "accum": 2,
    "error": 3,
    "snow": 4,
    "ice": 5,
    "freezing_rain": 6,
    "rain": 7,
}

ECMWF = {
    "pressure": 1,
    "temp": 2,
    "dew": 3,
    "wind_u": 4,
    "wind_v": 5,
    "intensity": 6,
    "accum": 7,
    "ptype": 8,
    "cloud": 9,
    "prob": 10,
    "accum_mean": 11,
    "accum_stddev": 12,
}

NBM = {
    "gust": 1,
    "temp": 2,
    "apparent": 3,
    "dew": 4,
    "humidity": 5,
    "wind": 6,
    "bearing": 7,
    "accum": 8,
    "cloud": 9,
    "vis": 10,
    "weather": 11,
    "prob": 12,
    "intensity": 13,
    "rain": 14,
    "freezing_rain": 15,
    "snow": 16,
    "ice": 17,
    "solar": 18,
    "cape": 19,
}

NBM_FIRE_INDEX = 1

RTMA_RU = {
    "vis": 1,
    "gust": 2,
    "pressure": 3,
    "temp": 4,
    "dew": 5,
    "humidity": 6,
    "cloud": 7,
    "wind_u": 8,
    "wind_v": 9,
}
