# Model variable indices for human-readable access
# Add more mappings as needed for each model

HRRR_SUBH = {
    "gust": 1,
    "pressure": 2,
    "temperature": 3,
    "dew_point": 4,
    "wind_u": 5,
    "wind_v": 6,
    "precip_rate": 7,
    "snow": 8,
    "ice": 9,
    "freezing_rain": 10,
    "rain": 11,
    "refc": 12,
    "accumulation": 13,
    "visibility": 14,
    "specific_humidity": 15,
    "solar": 16,
}
HRRR = {
    "visibility": 1,
    "gust": 2,
    "pressure": 3,
    "temperature": 4,
    "dew_point": 5,
    "humidity": 6,
    "wind_u": 7,
    "wind_v": 8,
    "precip_rate": 9,
    "accumulation": 10,
    "snow": 11,
    "ice": 12,
    "freezing_rain": 13,
    "rain": 14,
    "cloud_cover": 15,
    "smoke": 16,
    "refc": 17,
    "solar": 18,
    "cape": 19,
}

GFS = {
    "visibility": 1,
    "gust": 2,
    "pressure": 3,
    "temperature": 4,
    "dew_point": 5,
    "humidity": 6,
    "apparent_temperature": 7,
    "wind_u": 8,
    "wind_v": 9,
    "precip_rate": 10,
    "accumulation": 11,
    "snow": 12,
    "ice": 13,
    "freezing_rain": 14,
    "rain": 15,
    "ozone": 16,
    "cloud_cover": 17,
    "uv": 18,
    "storm_distance": 19,
    "storm_direction": 20,
    "refc": 21,
    "solar": 22,
    "cape": 23,
}

GEFS = {
    "pop": 1,
    "accumulation": 2,
    "error": 3,
    "snow": 4,
    "ice": 5,
    "freezing_rain": 6,
    "rain": 7,
}

NBM = {
    "gust": 1,
    "temperature": 2,
    "apparent_temperature": 3,
    "dew_point": 4,
    "humidity": 5,
    "wind_speed": 6,
    "wind_direction": 7,
    "accumulation": 8,
    "cloud_cover": 9,
    "visibility": 10,
    "weather": 11,
    "pop": 12,
    "precip_rate": 13,
    "rain": 14,
    "freezing_rain": 15,
    "snow": 16,
    "ice": 17,
    "solar": 18,
    "cape": 19,
}

NBM_FIRE_INDEX = 1
